### ISSUE TITLE
Polygon erigon3 high DISK I/O Utilization

### ISSUE THREAD

**Issue by insider89** [erigontech/erigon#11615]
#### System information

Erigon version: `v3.0.0-alpha2`

OS & Version: Linux(k9s cluster 1.29)

Commit hash: 6124a58f7f6560641e25181e05e74b3bbfdaa95a

Erigon Command (with flags/config): 
        - --chain=bor-mainnet
        - --txpool.nolocals
        - --db.pagesize=16k
        - --private.api.addr=0.0.0.0:9090
        - --nat=extip:YOU_EXTERNAL_IP
        - --authrpc.vhosts=*
        - --authrpc.jwtsecret=/home/erigon/.local/share/erigon/jwtsecret
        - --authrpc.addr=0.0.0.0
        - --datadir=/home/erigon/.local/share/erigon
        - --db.size.limit=15TB
        - --metrics
        - --port=30843
        - --p2p.allowed-ports=30843
        - --p2p.allowed-ports=30844
        - --p2p.allowed-ports=30845
        - --metrics.addr=0.0.0.0
        - --metrics.port=6060
        - --torrent.download.rate=1000mb
        - --http.api=admin,net,eth,erigon,web3,net,debug,trace,txpool,engine,ots
        - --http.addr=0.0.0.0
        - --http.vhosts=*
        - --http.corsdomain=*
        - --rpc.batch.limit=1000
        - --bodies.cache=5G
        - --ws
        - --db.read.concurrency=1024
        - --rpc.batch.concurrency=64
        - --txpool.pricelimit=30000000000
        - --bor.milestone=false
        - --bor.heimdall=http://polygon-heimdall-rpc:1317/
        - --log.dir.path=/home/erigon/.local/share/erigon/logs

Consensus Layer: Caplin

Consensus Layer Command (with flags/config):

Chain/Network: 
Polygon

#### Expected behaviour
Disk I/O utilization less than 100%

#### Actual behaviour
Disk I/O utilization is 100%
<img width="933" alt="Screenshot 2024-08-14 at 14 32 45" src="https://github.com/user-attachments/assets/076566a9-8aed-4b1c-a0f9-7fcc7869f71a">

When I stop polygon erigon3 I see 10% of disk I/O utilization

#### Steps to reproduce the behaviour
Run it on the k8s cluster with NVME disk:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    pulumi.com/patchForce: "true"
  name: polygon-3-erigon3
  namespace: polygon
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: erigon3
      app.kubernetes.io/name: polygon-3-erigon3
  strategy:
    type: Recreate
  template:
    metadata:
      name: polygon-3
    spec:
      containers:
      - args:
        - --chain=bor-mainnet
        - --txpool.nolocals
        - --db.pagesize=16k
        - --private.api.addr=0.0.0.0:9090
        - --nat=extip:YOU_EXTERNAL_IP
        - --authrpc.vhosts=*
        - --authrpc.jwtsecret=/home/erigon/.local/share/erigon/jwtsecret
        - --authrpc.addr=0.0.0.0
        - --datadir=/home/erigon/.local/share/erigon
        - --db.size.limit=15TB
        - --metrics
        - --port=30843
        - --p2p.allowed-ports=30843
        - --p2p.allowed-ports=30844
        - --p2p.allowed-ports=30845
        - --metrics.addr=0.0.0.0
        - --metrics.port=6060
        - --torrent.download.rate=1000mb
        - --http.api=admin,net,eth,erigon,web3,net,debug,trace,txpool,engine,ots
        - --http.addr=0.0.0.0
        - --http.vhosts=*
        - --http.corsdomain=*
        - --rpc.batch.limit=1000
        - --bodies.cache=5G
        - --ws
        - --db.read.concurrency=1024
        - --rpc.batch.concurrency=64
        - --txpool.pricelimit=30000000000
        - --bor.milestone=false
        - --bor.heimdall=http://polygon-heimdall-rpc:1317/
        - --log.dir.path=/home/erigon/.local/share/erigon/logs
        command:
        - erigon
        image: docker.io/thorax/erigon:v3.0.0-alpha2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8545
          timeoutSeconds: 5
        name: polygon-3
        ports:
        - containerPort: 8545
          name: json-rpc
          protocol: TCP
        - containerPort: 42069
          name: snapsync
          protocol: TCP
        - containerPort: 42069
          name: snapsyncudp
          protocol: UDP
        - containerPort: 30843
          name: rlpx66
          protocol: TCP
        - containerPort: 30843
          name: discovery66
          protocol: UDP
        - containerPort: 30844
          name: rlpxunknown
          protocol: TCP
        - containerPort: 30844
          name: discoveryunkown
          protocol: UDP
        - containerPort: 30845
          name: rlpx67
          protocol: TCP
        - containerPort: 30845
          name: discovery67
          protocol: UDP
        - containerPort: 6060
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 12
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8545
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/erigon/.local/share/erigon
          name: storage
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: public-nodes-10
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 90
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: polygon-3-erigon3

```
