### ISSUE TITLE
New docker images break CI

### ISSUE THREAD

**Issue by yorickdowne** [erigontech/erigon#11932]
#### Issue

The `linux/amd64/v2` architecture on the new `latest` and `2.60.7` tags on `erigontech/erigon` fails on Github CI runners, with a note that no matching architecture was found.

#### Suggested solution

Use `linux/amd64` architecture like on the `main-latest` tag. This will allow the image to be pulled on a broad range of x64 implementations.

**Comment by lystopad** [comment]
Hi, @yorickdowne.

Please, provide peace of your workflow where I can see runner configuration and how docker image pulled.

**Comment by yorickdowne** [comment]
```
jobs:
  test-lodestar-erigon:
    if: |
      contains(github.event.pull_request.labels.*.name, 'test-lodestar') ||
      contains(github.event.pull_request.labels.*.name, 'test-erigon') ||
      contains(github.event.pull_request.labels.*.name, 'test-all') ||
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Create .env file
        run: cp default.env .env
      - name: Set Lodestar/Erigon
        run: |
          source ./.github/helper.sh
          COMPOSE_FILE=lodestar.yml:erigon.yml
          var=COMPOSE_FILE
          set_value_in_env
          FEE_RECIPIENT=0xDccf8451070a86183eE70D330C4c43b686E9CF86
          var=FEE_RECIPIENT
          set_value_in_env
      - name: Start Lodestar/Erigon
        run: ./ethd up
```

`./ethd up` in turn is `docker compose up -d`

The `erigon.yml` contains this for the image:

```
services:
  execution:
    restart: "unless-stopped"
    build:
      context: ./erigon
      dockerfile: ${ERIGON_DOCKERFILE}
      args:
        - BUILD_TARGET=${ERIGON_SRC_BUILD_TARGET:-'$(git describe --tags $(git rev-list --tags --max-count=1))'}
        - SRC_REPO=${ERIGON_SRC_REPO:-https://github.com/ledgerwatch/erigon}
        - DOCKER_TAG=${ERIGON_DOCKER_TAG:-stable}
        - DOCKER_REPO=${ERIGON_DOCKER_REPO:-thorax/erigon}
    stop_grace_period: 5m
    image: erigon:local
```

The `Dockerfile.binary` that would be referenced from this contains:

```
ARG DOCKER_TAG=latest
ARG DOCKER_REPO=erigontech/erigon

FROM ${DOCKER_REPO}:${DOCKER_TAG}
```

The defaults don't apply here because we have this from the `.env`:

```
ERIGON_DOCKER_TAG=latest                                                                                                
ERIGON_DOCKER_REPO=erigontech/erigon                                                                                    
ERIGON_DOCKERFILE=Dockerfile.binary
```

This is how the action fails:

```
#6 [execution internal] load metadata for docker.io/erigontech/erigon:latest
#6 ERROR: no match for platform in manifest: not found
failed to solve: erigontech/erigon:latest: failed to resolve source metadata for docker.io/erigontech/erigon:latest: no match for platform in manifest: not found
```

The platform for `latest` is `linux/amd64/v2`. I am convinced that if it was `linux/amd64`, this would work in Github's `ubuntu:latest` runner. 

The `thorax/erigon` repo works with the same runner and same workflow/action.
