### ISSUE TITLE
follow up on moving `trie` to `erigon-lib`

### ISSUE THREAD

**Issue by AskAlexSharov** [erigontech/erigon#12883]
follow-up on https://github.com/erigontech/erigon/pull/12879
1. to remove next lines from `/erigon-lib/.golangci.yml`:
```
    - path: rlp
      linters:
        - errorlint
    - path: bitutil
      linters:
        - errorlint
```
