### ISSUE TITLE
Include CURL on docker release image for health check purpose

### ISSUE THREAD

**Issue by tornadocontrib** [erigontech/erigon#13417]
Docker release images should have `curl` tool bundled like images built from source.

I personally use the following healthcheck script on docker and it is very useful when you want externalcl to connect only when the auth port is opened.

```
healthcheck:
    test: ["CMD-SHELL", "curl -X POST -H \"Content-Type: application/json\" --data \"{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"params\":[],\"id\":67}\" http://localhost:8545"]
    interval: 30s
    timeout: 5s
    retries: 10
    start_period: 20s

depends_on:
    erigon:
        condition: service_healthy
```

**Comment by tornadocontrib** [comment]
This works great on geth though

```
healthcheck:
      test: ["CMD-SHELL", "geth attach --exec 'net.peerCount'"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 20s
```
