### ISSUE TITLE
Holesky network returns hoodie chain id

### ISSUE THREAD

**Issue by jozsefb** [erigontech/erigon#14559]
#### System information

Erigon version: `v3.0.1`
OS & Version: Debian
Commit hash: 18e202dfb0b07848126e5d1c10972d3eb8acb9b8
Erigon Command (with flags/config):
```
    command: >
      --externalcl
      --chain=holesky
      --datadir=/erigon
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.api=engine,eth,web3,net
      --ws
      --ws.port=8546
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.vhosts=erigon
      --authrpc.jwtsecret=/erigon/jwt.hex
      --torrent.download.rate=512mb
```
Consensus Layer: Lighthouse

Consensus Layer Command (with flags/config):
```
      lighthouse bn
      --network holesky
      --datadir /lighthouse
      --execution-endpoint http://erigon:8551
      --execution-jwt /jwt.hex
      --http
      --http-address 0.0.0.0
      --metrics
      --allow-insecure-genesis-sync
```

Chain/Network: holesky

#### Expected behaviour

The two clients should synch.

#### Actual behaviour

Getting errors on both clients:

On lightouse:
```
Apr 11 11:34:23.168 WARN Invalid execution chain ID. Please switch to correct chain ID on endpoint, received: Custom(560048), expected: Custom(17000), endpoint: http://erigon:8551/, auth=true, service: deposit_contract_rpc
Apr 11 11:34:23.168 ERRO Error updating deposit contract cache   error: Invalid endpoint state: WrongChainId, retry_millis: 60000, service: deposit_contract_rpc
```

On erigon:
```
[WARN] [04-11|11:31:38.571] flag --externalcl was provided, but no CL seems to be connected.
[WARN] [04-11|11:31:48.562] [p2p] No GoodPeers
```

#### Steps to reproduce the behaviour

New installation. Using docker images.

Full docker compose:

```yaml
services:
  # erigon
  erigon:
    image: erigontech/erigon:latest
    container_name: erigon
    restart: unless-stopped
    ports:
      - "8545:8545"     # HTTP-RPC
      - "8546:8546"     # WS-RPC
      - "30303:30303"   # P2P
      - "30303:30303/udp"
      - "8551:8551"     # AUTH RPC
    networks:
      - validators
    volumes:
      - ./erigon/data:/erigon
    command: >
      --externalcl
      --chain=holesky
      --datadir=/erigon
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.api=engine,eth,web3,net
      --ws
      --ws.port=8546
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.vhosts=erigon
      --authrpc.jwtsecret=/erigon/jwt.hex
      --torrent.download.rate=512mb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 5
  # lighthouse
  lighthouse:
    image: sigp/lighthouse:latest
    container_name: lighthouse
    restart: unless-stopped
    depends_on:
      - erigon
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "9001:9001/udp"
      - "5052:5052"     # HTTP API
    networks:
      - validators
    volumes:
      - ./lighthouse/data:/lighthouse
      - ./erigon/data/jwt.hex:/jwt.hex:ro
    command: >
      lighthouse bn
      --network holesky
      --datadir /lighthouse
      --execution-endpoint http://erigon:8551
      --execution-jwt /jwt.hex
      --http
      --http-address 0.0.0.0
      --metrics
      --allow-insecure-genesis-sync

networks:
  validators:
```
