### ISSUE TITLE
Websocket hang after error while notifying subscription

### ISSUE THREAD

**Issue by wojski** [erigontech/erigon#5608]
#### System information

Erigon version: erigon/2022.09.3/linux-amd64/go1.19.1

OS & Version:Linux 

Commit hash :  https://hub.docker.com/layers/thorax/erigon/v2022.09.03/images/sha256-a8d14345cf3b8f089e38b660508a11d9d7c7dd659d6906372aab187fbc8ee083?context=explore

#### Expected behaviour

Websocket with message:

`{"jsonrpc":"2.0","id": 1, "method": "eth_subscribe", "params": ["newHeads"]}`

Should return new blocks.

#### Actual behaviour

After some time no new messages came from WS.

In rpcDaemon I can find log:
[WARN] [10-03|21:31:53.506] error while notifying subscription       err="write tcp 172.22.0.10:8545->**xxxxxxxx**:55508: write: connection timed out"

RPC endpoint working correctly.
WS is no longer responsible (I can connect to it, but no messages received)
Its working again after restart container.

RPCNode:

```
  erigon:
    image: thorax/erigon:v2022.09.03
    container_name: erigon_eth
    command: erigon --metrics  --metrics.addr=0.0.0.0 --private.api.addr=0.0.0.0:9090 --metrics.port=6060 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061
             --authrpc.jwtsecret=/home/lighthouse/jwtsecret.hex --authrpc.port=8551 --authrpc.addr="0.0.0.0" --authrpc.vhosts="*"
             --override.terminaltotaldifficulty=0xc70d808a128d7380000 --db.read.concurrency=2000 --rpc.batch.concurrency=10000
    volumes:
      - /srv/crypto/erigon/eth/data:/home/erigon/.local/share/erigon
      - /srv/crypto/erigon/eth/lighthouse:/home/lighthouse
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
      - "30304:30304/tcp"
      - "30304:30304/udp"
      - "9091:9090"
    restart: unless-stopped 
```
RPCDeamon:

```
rpcdaemon:
    image: thorax/erigon:v2022.09.03
    container_name: erigon_eth_rpcdaemon_1
    command: rpcdaemon --datadir=/home/erigon/.local/share/erigon --private.api.addr=erigon:9090  --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --verbosity=2 --rpc.batch.concurrency=8
             --http.api=eth,debug,net,web3,trace --ws --db.read.concurrency=2000 --rpc.batch.concurrency=60000 --ws.compression=true
    pid: service:erigon # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
    volumes:
      - /srv/crypto/erigon/eth/data:/home/erigon/.local/share/erigon
    ports:
      - "8550:8545"
    restart: unless-stopped
```

#### Steps to reproduce the behaviour

Use WS for some time with:

`{"jsonrpc":"2.0","id": 1, "method": "eth_subscribe", "params": ["newHeads"]}`

#### Backtrace

````
[WARN] [10-03|21:31:53.506] error while notifying subscription       err="write tcp 172.22.0.10:8545->**xxxxxxxx**:55508: write: connection timed out"
````

(Same issue on 09.01)
